### ISSUE TITLE
The bot isn't start

### ISSUE THREAD

**Issue by ikr4-m** [belguawhale/Discord-Werewolf#28]
```
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 224, in _run_event
    yield from coro(*args, **kwargs)
  File "bot.py", line 89, in on_ready
    for role in client.get_server(WEREWOLF_SERVER).role_hierarchy:
AttributeError: 'Client' object has no attribute 'get_server'
```
I have the code error like this.

**Comment by Zephyrkul** [comment]
(Bit late on this but just in case someone else has the same issue:)
You have the wrong version of discord.py installed. Use the async version, not the rewrite version.
