### ISSUE TITLE
Can't use command

### ISSUE THREAD

**Issue by jxlah** [belguawhale/Discord-Werewolf#45]
cmd message

Active code page: 65001
~~~~~~NEW INSTANCE~~~~~~
BACKING UP SETTINGS
Logged in as
Werewolf
542775053108903947
------
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\jxlah\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "bot.py", line 91, in on_ready
    for role in client.get_server(WEREWOLF_SERVER).role_hierarchy:
AttributeError: 'NoneType' object has no attribute 'role_hierarchy'

already downloaded asyncio and discord.py but no commands work.

**Comment by PokeSvorlds** [comment]
I believe you failed to set up config.py completely? It doesnt look like put in the server ID for WEREWOLF_SERVER.

**Comment by jxlah** [comment]
> I believe you failed to set up config.py completely? It doesnt look like put in the server ID for WEREWOLF_SERVER.

ah, can't believe i missed that. works perfectly now thanks!
