### ISSUE TITLE
Cannot start game

### ISSUE THREAD

**Issue by PssbleTrngle** [belguawhale/Discord-Werewolf#58]
Hi, I am getting the following error when I try to start a game.
I am using python 3.6 and the bot has admin rights

```python
Traceback (most recent call last):
  File "/werewolf/bot.py", line 3038, in parse_command
    await commands[commandname][0](message, parameters)
  File "/werewolf/bot.py", line 510, in cmd_start
    await run_game()
  File "/werewolf/bot.py", line 4203, in run_game
    client.get_server(WEREWOLF_SERVER).get_member(OWNER_ID).name))
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by PssbleTrngle** [comment]
This is my config

```python
OWNER_ID = 'Nik#0665'
BOT_PREFIX = 'w.'
TOKEN = '******'
GAME_CHANNEL = '******'
DEBUG_CHANNEL = '******'
WEREWOLF_SERVER = '******'
PLAYERS_ROLE_NAME = 'Furry'
ADMINS_ROLE_NAME = 'Hight Priest'
WEREWOLF_NOTIFY_ROLE_NAME = 'Waiting'
ADMINS = ['Nik#0665']
IGNORE_LIST = []
TOKENS_GIVEN = 5
TOKEN_RESET = 10
IGNORE_THRESHOLD = 7
NOTIFY_FILE = 'logs/notify.log'
BACKUP_INTERVAL = 300
MESSAGE_LANGUAGE = 'en'
LOG_FILE = 'logs/debug.log'
MIN_LOG_LEVEL = 1
STASIS_FILE = 'stasis.json'
PLAYING_MESSAGE = 'werewolf. Use {0}join to play'.format(BOT_PREFIX)
```

**Comment by PssbleTrngle** [comment]
Looks like it cannot find the speicifed owner, but the discord tag in the config is correct

**Comment by Xinverse** [comment]
Your OWNER_ID, as well your ADMINS variables, are not set up correctly. Enable developer mode on your Discord client and retrieve the unique ID number of your owner account as well as the admin account. The ID string looks something like this: "726522990778384405". You don't have to add the owner as admin either.

**Comment by Xinverse** [comment]
You can join our server to ask for help with setup: discord.gg/Kn3BPdG

**Comment by PssbleTrngle** [comment]
Yes I just realized, thank you

**Comment by PssbleTrngle** [comment]
literally the second you commented
