### ISSUE TITLE
Bot Restarting Error?

### ISSUE THREAD

**Issue by Timmooo** [belguawhale/Discord-Werewolf#80]
Get the following error using the most recent version. Have installed the Xinverse version of discord.py

Any suggestions on how to fix/what is causing it? 

`Traceback (most recent call last):
  File "./bot.py", line 6429, in <module>
    client.loop.run_until_complete(client.start(TOKEN))
  File "/home/tim/.pyenv/versions/3.5.7/lib/python3.5/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/home/tim/.pyenv/versions/3.5.7/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/home/tim/.pyenv/versions/3.5.7/lib/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "/home/tim/.pyenv/versions/3.5.7/lib/python3.5/site-packages/discord/client.py", line 490, in start
    yield from self.connect()
  File "/home/tim/.pyenv/versions/3.5.7/lib/python3.5/site-packages/discord/client.py", line 448, in connect
    yield from self.ws.poll_event()
  File "/home/tim/.pyenv/versions/3.5.7/lib/python3.5/site-packages/discord/gateway.py", line 426, in poll_event
    yield from self.received_message(msg)
  File "/home/tim/.pyenv/versions/3.5.7/lib/python3.5/site-packages/discord/gateway.py", line 337, in received_message
    raise ResumeWebsocket()
NameError: name 'ResumeWebsocket' is not defined
`

**Comment by Timmooo** [comment]
Have updated to python3.6 and latest pull in case it would fix this. Still getting this error sadly.

`Traceback (most recent call last):
  File "./bot.py", line 6399, in <module>
    client.loop.run_until_complete(client.start(TOKEN))
  File "/home/tim/.pyenv/versions/3.6.8/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/tim/.pyenv/versions/3.6.8/lib/python3.6/site-packages/discord/client.py", line 490, in start
    yield from self.connect()
  File "/home/tim/.pyenv/versions/3.6.8/lib/python3.6/site-packages/discord/client.py", line 448, in connect
    yield from self.ws.poll_event()
  File "/home/tim/.pyenv/versions/3.6.8/lib/python3.6/site-packages/discord/gateway.py", line 426, in poll_event
    yield from self.received_message(msg)
  File "/home/tim/.pyenv/versions/3.6.8/lib/python3.6/site-packages/discord/gateway.py", line 337, in received_message
    raise ResumeWebsocket()
NameError: name 'ResumeWebsocket' is not defined
`
