### ISSUE TITLE
Error Client doesn't have attribute send.message

### ISSUE THREAD

**Issue by EdizCinbas** [belguawhale/Discord-Werewolf#86]
Logged in As:
Werewolf Bot
754698300703113246
------
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oecin\Desktop\Werewolf Bot\Discord-Werewolf-master\bot.py", line 99, in on_ready
    await log(1, 'on_ready triggered!')
  File "C:\Users\oecin\Desktop\Werewolf Bot\Discord-Werewolf-master\bot.py", line 3147, in log
    await send_long_log_helper(client.get_channel(DEBUG_CHANNEL), logmsg)
  File "C:\Users\oecin\Desktop\Werewolf Bot\Discord-Werewolf-master\bot.py", line 3123, in send_long_log_helper
    await client.send_message(channel, post)
AttributeError: 'Client' object has no attribute 'send_message'

- This is the error message I am running in Sublime Text 3

**Comment by Psych0Foxx** [comment]
Hey,

did you solved the Problem in the meantime?
